esphome:
  name: inverter
  friendly_name: Inverter

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret inverter_api_key

ota:
  - platform: esphome
    password: !secret inverter_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Inverter Fallback Hotspot"
    password: !secret inverter_ap_password
  
captive_portal:
  
output:
  - platform: gpio
    pin:
      number: 8
      mode: output
    id: led_id

interval:
  - interval: 1000ms
    then:
      - output.turn_on: led_id
      - delay: 250ms
      - output.turn_off: led_id

# light:
#   - platform: status_led
#     pin:
#       number: 8
#       inverted: true
#     id: led_id
#     name: "LED"

    # effects:
    #   - pulse:
    #       name: "Slow Breathing"
    #       transition_length: 1s
    #       update_interval: 1s
    #       min_brightness: 20%
    #       max_brightness: 100%

    # optimistic: yes  # Optional: For faster response, especially if using with automations

  # - platform: template
  #   name: "Blinking LED"
  #   id: led_blink
  #   optimistic: yes
  #   turn_on_action:
  #     - switch.turn_on: led_switch
  #     - delay: 500ms
  #     - switch.turn_off: led_switch
  #     - delay: 500ms
  #   turn_off_action:
  #     - switch.turn_off: led_switch


# script:
#   - id: make_status_breathe
#     mode: queued
#     then:
#       - light.turn_on:
#         id: led_id
#         effect: "Slow Breathing"


packages:
  # base: !include base-config.yaml
  inverter1: !include
    file: single-pow-hvm62k-48v-lip.yaml
    vars:
      tx_pin: GPIO21
      rx_pin: GPIO20
      id_suffix: "_A"
      name_suffix: " A"
  inverter2: !include
    file: single-pow-hvm62k-48v-lip.yaml
    vars:
      tx_pin: GPIO10
      rx_pin: GPIO9
      id_suffix: "_B"
      name_suffix: " B"

substitutions:
  name_prefix: "⭐️ "

sensor:

  - platform: combination
    type: median
    name: "${name_prefix}Mains Voltage"
    id: Mains_Voltage
    sources:
      - source: Mains_Voltage_A
      - source: Mains_Voltage_B

  - platform: combination
    type: median
    name: "${name_prefix}Mains Frequency"
    id: Mains_Frequency
    sources:
      - source: Mains_Frequency_A
      - source: Mains_Frequency_B

  - platform: combination
    type: sum
    name: "${name_prefix}Mains Power"
    id: Mains_Power
    sources:
      - source: Mains_Power_A
      - source: Mains_Power_B

  - platform: combination
    type: mean
    name: "${name_prefix}Inverter Voltage"
    id: Inverter_Voltage
    sources:
      - source: Inverter_Voltage_A
      - source: Inverter_Voltage_B

  - platform: combination
    type: sum
    name: "${name_prefix}Inverter Current"
    id: Inverter_Current
    sources:
      - source: Inverter_Current_A
      - source: Inverter_Current_B

  - platform: combination
    type: sum
    name: "${name_prefix}Inverter Power"
    id: Inverter_Power
    sources:
      - source: Inverter_Power_A
      - source: Inverter_Power_B

  - platform: combination
    type: mean
    name: "${name_prefix}Inverter Load"
    id: Inverter_Load_Percentage
    sources:
      - source: Inverter_Load_Percentage_A
      - source: Inverter_Load_Percentage_B

  - platform: combination
    type: sum
    name: "${name_prefix}Output Active Power"
    id: Output_Active_Power
    sources:
      - source: Output_Active_Power_A
      - source: Output_Active_Power_B

  - platform: combination
    type: sum
    name: "${name_prefix}Output Apparent Power"
    id: Output_Apparent_Power
    sources:
      - source: Output_Apparent_Power_A
      - source: Output_Apparent_Power_B

  - platform: combination
    type: mean
    name: "${name_prefix}Output Voltage"
    id: Output_Voltage
    sources:
      - source: Output_Voltage_A
      - source: Output_Voltage_B

  - platform: combination
    type: sum
    name: "${name_prefix}Output Current"
    id: Output_Current
    sources:
      - source: Output_Current_A
      - source: Output_Current_B
  
  - platform: combination
    type: mean
    name: "${name_prefix}Battery Voltage"
    id: Battery_Voltage
    sources:
      - source: Battery_Voltage_A
      - source: Battery_Voltage_B

  - platform: combination
    type: sum
    name: "${name_prefix}Battery Current"
    id: Battery_Current
    sources:
      - source: Battery_Current_A
      - source: Battery_Current_B

  - platform: combination
    type: sum
    name: "${name_prefix}Battery Power"
    id: Battery_Power
    sources:
      - source: Battery_Power_A
      - source: Battery_Power_B

  - platform: combination
    type: sum
    name: "${name_prefix}PV Power"
    id: PV_Power
    sources:
      - source: PV_Power_A
      - source: PV_Power_B

  - platform: combination
    type: sum
    name: "${name_prefix}PV Charging Power"
    id: PV_Charging_Power
    sources:
      - source: PV_Charging_Power_A
      - source: PV_Charging_Power_B

  - platform: combination
    type: sum
    name: "${name_prefix}PV Charging Current"
    id: PV_Charging_Current
    sources:
      - source: PV_Charging_Current_A
      - source: PV_Charging_Current_B

  # - platform: combination
  #   type: sum
  #   name: "${name_prefix}NAME"
  #   id: ID
  #   sources:
  #     - source: ID_A
  #     - source: ID_B

    
# sensor:

  - platform: uptime
    name: "Uptime"
    entity_category: "diagnostic"
    device_class: duration
    update_interval: 1s
  - platform: wifi_signal
    name: "RSSI"
    id: wifi_rssi
    entity_category: "diagnostic"
    update_interval: 60s

# esp32:
#   board: esp32-c3-devkitm-1
#   framework:
#     type: arduino
